# Ref: https://yamllint.readthedocs.io/en/stable/configuration.html
---
extends: default

rules:
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  line-length:
    max: 300
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start:
    level: warning
  empty-lines: enable
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  hyphens: enable
  indentation:
    spaces: 2
    level: error
    indent-sequences: true
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
    level: error
  octal-values: disable
  quoted-strings: disable
  trailing-spaces:
    level: error
  truthy:
    level: error

ignore: |
  .tox
  .venv
  tools/
  .github/
...
