---
- name: "caddy | Create app directories"
  file:
    path: "{{ caddy_data_dir }}"
    state: directory
    mode: '0755'

- name: "caddy | Set caddyfile template name"
  set_fact:
    caddyfile_name: >-
      {{ 'Caddyfile.j2'
         if (sso_provider is not defined or (sso_provider | string | length == 0))
         else ('Caddyfile-' ~ (sso_provider | upper) ~ '.j2') }}

- name: "caddy | Template Docker compose and caddy configs"
  template:
    src: "{{ item.src }}"
    dest: "{{ caddy_data_dir }}/{{ item.dst }}"
    mode: "{{ item.mode }}"
    backup: true
  loop:
    - {src: docker-compose.yml.j2, dst: docker-compose.yml, mode: "0644"}
    - {src: "{{ caddyfile_name }}", dst: Caddyfile, mode: "0644"}
  notify: reload caddy

- name: Flush handlers to restart the app now
  ansible.builtin.meta: flush_handlers

- name: "caddy | Start services with docker-compose"
  community.docker.docker_compose_v2:
    project_src: "{{ caddy_data_dir }}"
    files:
      - "docker-compose.yml"
    state: present
