---
galaxy_info:
  role_name: caddy
  namespace: cantina
  author: v.kamerdinerov
  description: caddy role (cantina.core)
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags: []
dependencies: []
...
