---
- name: "postgres | Create database user - {{ item.user }}"
  community.postgresql.postgresql_user:
    login_host: 127.0.0.1
    login_port: "{{ postgres_port }}"
    login_user: "{{ postgres_init_user }}"
    login_password: "{{ vault_postgres_standalone_pg_password }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    state: present
  no_log: false

- name: "postgres | Create database - {{ item.db }}"
  community.postgresql.postgresql_db:
    login_host: 127.0.0.1
    login_port: "{{ postgres_port }}"
    login_user: "{{ postgres_init_user }}"
    login_password: "{{ vault_postgres_standalone_pg_password }}"
    name: "{{ item.db }}"
    owner: "{{ item.user }}"
    state: present


- name: "postgres | Grant privileges for db {{ item.db }} and user {{ item.user }}"
  community.postgresql.postgresql_privs:
    login_host: 127.0.0.1
    login_port: "{{ postgres_port }}"
    login_user: "{{ postgres_init_user }}"
    login_password: "{{ vault_postgres_standalone_pg_password }}"
    database: "{{ item.db }}"
    roles: "{{ item.user }}"
    privs: ALL
    type: database
    state: present
