---
name: lint

on:
  push:
    branches:
      - main
    paths:
      - 'roles/**'
  pull_request:
    paths:
      - 'roles/**'

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install yamllint
        run: pip install --use-pep517 yamllint
      - name: Run yamllint
        run: yamllint .

  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install --use-pep517 -r requirements.txt
      - name: Install required collections
        run: ansible-galaxy collection install -r requirements.yml
      - name: Run ansible-lint
        run: ansible-lint -c tools/ansible-lint/.ansible-lint.yml --force-color roles/
...
